/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type {
  NounsTokenLike,
  NounsTokenLikeInterface,
} from '../../../../contracts/governance/NounsDAOInterfaces.sol/NounsTokenLike'

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'blockNumber',
        type: 'uint256',
      },
    ],
    name: 'getPriorVotes',
    outputs: [
      {
        internalType: 'uint96',
        name: '',
        type: 'uint96',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [
      {
        internalType: 'uint96',
        name: '',
        type: 'uint96',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]

export class NounsTokenLike__factory {
  static readonly abi = _abi
  static createInterface(): NounsTokenLikeInterface {
    return new utils.Interface(_abi) as NounsTokenLikeInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): NounsTokenLike {
    return new Contract(address, _abi, signerOrProvider) as NounsTokenLike
  }
}
