/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type {
  Administered,
  AdministeredInterface,
} from '../../../../contracts/test/NounsDAOExecutorHarness.sol/Administered'

const _abi = [
  {
    inputs: [],
    name: '_acceptAdmin',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]

export class Administered__factory {
  static readonly abi = _abi
  static createInterface(): AdministeredInterface {
    return new utils.Interface(_abi) as AdministeredInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Administered {
    return new Contract(address, _abi, signerOrProvider) as Administered
  }
}
